### ISSUE TITLE
Mobilyzer crashing on throughput tests on certain devices

### ISSUE THREAD

**Issue by andrewkim823** [mobilyzer/Mobilyzer#5]
A My Speed Test user reported our app crashing while performing a throughput test.

Android version: 5.0
Device: Galaxy S5
 
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.num/com.num.view.activities.ThroughputActivity}: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.mobilyzer.MeasurementScheduler (has extras) }
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2728)
at android.app.ActivityThread.access$900(ActivityThread.java:172)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5837)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.mobilyzer.MeasurementScheduler (has extras) }
at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:2040)
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:2078)
at android.app.ContextImpl.startService(ContextImpl.java:2053)
at android.content.ContextWrapper.startService(ContextWrapper.java:533)
at com.mobilyzer.api.API.startAndBindService(API.java:210)
at com.mobilyzer.api.API.<init>(API.java:122)
at com.mobilyzer.api.API.getAPI(API.java:135)
at com.num.view.activities.ThroughputActivity.onCreate(ThroughputActivity.java:63)
at android.app.Activity.performCreate(Activity.java:6221)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2614)
... 10 more

I don't have much more information here, but I believe this could be a Lollipop specific issue.
Please investigate this and I'll try to provide as much information as possible.

**Comment by anikravesh** [comment]
Fixed.
